
apiVersion: v1
kind: Service
metadata:
  name: movie-app
  namespace: default
  labels:
    app: movie-app
spec:
  type: ClusterIP          # Internal service (best for Argo + Prod)
  selector:
    app: movie-app         # âœ… MUST match pod labels
  ports:
    - name: http
      port: 80             # Service port
      targetPort: 5000     # Container port
      protocol: TCP
